project:
  type: website
  output-dir: docs

website:
  title: "Quarto_PT2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt
    papersize: A4
    toc: true
    number-sections: true
    fontfamily: univers






